version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - odoo-net
    volumes:
      - postgres-data:/var/lib/postgresql/data

  odoo:
    image: odoo:17
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      HOST: db
      USER: ${POSTGRES_USER}
      PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - odoo-net
    volumes:
      - odoo-filestore:/var/lib/odoo

  nginx:
    image: nginx:latest
    depends_on:
      - odoo
    ports:
      - "80:80"
    volumes:
      - ./nginx/odoo.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - odoo-net

networks:
  odoo-net:
    driver: bridge

volumes:
  postgres-data:
  odoo-filestore:
